version: "3.9"

services:
  db:
    image: postgres:13
    command: ["postgres", "-c", "fsync=0", "-c", "full_page_writes=off", "-c", "bgwriter_lru_maxpages=0", "-c", "synchronous_commit=off", "-c", "log_statement=all", "-c", "wal_level=logical"]
    ports:
      - "5435:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=12345
